dbt_project:
  outputs:
    dev:
      type: trino
      method: none
      host: trino
      port: 8080
      user: cigi
      catalog: nessie       # catalog Trino đã config
      schema: gold           
      threads: 4
  target: dev
